🔀 :: (#23) Home UI
team-xquare/xquare-android pull request #24
Opened 2022-06-15 07:27 UTC by JaewonKim04

홈화면 구현을 완료했습니다.

2022-06-16 14:28 UTC, shw0471 requested changes

2022-06-16 14:28 UTC, shw0471 commented on app/src/main/java/com/xquare/xquare_android/theme/Color.kt
> +val Gray700 = Color(0xFF5C5961)
제가 내일 디자인시스템 변경사항 반영해서 배포할건데
배포되면 디자인 시스템에 있는 Gray로 바꿔주세요

2022-06-20 07:33 UTC, JaewonKim04 commented on app/src/main/java/com/xquare/xquare_android/theme/Color.kt
> +val Gray700 = Color(0xFF5C5961)
ㅇㅋ

2022-07-05 11:22 UTC, shw0471 approved these changes

2022-07-05 11:22 UTC, merged